# Generated by Django 5.1 on 2024-09-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employ', 'Employ')], default='employ', max_length=20),
        ),
    ]
