# Generated by Django 5.1 on 2024-09-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0002_alter_menuitem_print_alter_modifier_aditional_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='print',
            new_name='price',
        ),
    ]
